### ISSUE TITLE
OAI SA + open5gs configs.

### ISSUE THREAD

**Issue by liuwei-network** [s5uishida/open5gs_epc_oai_sample_config#5]
Hi, thanks for offering these configs, they help me a lot.

I am recently building a 5G SA environment using open5gs, OAI gNB, COTS UE and have encountered many issues. Do you have any plans to provide configs for this environment?

Thanks in advance.

**Comment by s5uishida** [comment]
@VLiu7 

I have no plan for now.

**Comment by liuwei-network** [comment]
Thanks for your reply!
